services:
  minio:
    image: minio/minio
    container_name: climate-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:16
    container_name: climate-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: climate_db
      POSTGRES_USER: climate_user
      POSTGRES_PASSWORD: climate_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  minio_data:
  postgres_data: